version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: dmpropane_postgres
    restart: always
    environment:
      POSTGRES_USER: dmpropane_user
      POSTGRES_PASSWORD: dmpropane_password
      POSTGRES_DB: dmpropane_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
